export const motivationalPhrases: string[] = [
  "🌟 Vos sos tu único límite. Rompelo.",
  "🔥 Cada día es una nueva oportunidad para brillar, che.",
  "💪 La disciplina te lleva más lejos que las ganas.",
  "🚀 Arrancá. El resto se acomoda solo.",
  "🌈 Los sueños grandes piden acción diaria.",
  "⚡ Lo que hacés hoy construye tu mañana.",
  "🎯 Apuntá al progreso, no a la perfección.",
  "🌅 Esta mañana es el comienzo de algo increíble.",
  "💎 Podés más de lo que creés, en serio.",
  "🏆 Los campeones se hacen en los momentos difíciles.",
  "🌱 Cada paso cuenta. Seguí adelante.",
  "✨ Hacé de hoy algo de lo que te vayas a enorgullecer.",
  "🦁 Tené el coraje de tus ambiciones.",
  "🎶 La vida premia a los que se mueven.",
  "🌊 Sé la ola, no la espuma.",
  "🔑 El éxito es la suma de pequeños esfuerzos repetidos.",
  "🧠 Tu cabeza es tu superpoder. Usala bien.",
  "🌻 Florecé donde estás plantado.",
  "⭐ Un día bien empezado está medio ganado.",
  "🦋 La transformación empieza con una decisión.",
  "🏔️ Las mejores vistas vienen de las subidas más duras.",
  "💡 Una idea sin acción es solo un sueño. Actuá.",
  "🎁 Cada mañana es un regalo. Abrilo con intención.",
  "🌙 Ayer ya fue. Hoy es tu turno.",
  "🏄 Montate a tus oportunidades, no las dejes pasar.",
  "🦅 Volá alto. Siempre más alto.",
  "💫 No estás atrasado. Estás justo donde tenés que estar.",
  "🎯 Concentrarte en lo que podés controlar es el juego.",
  "🌍 Cambiá tu día, cambiás tu vida.",
  "🔓 Soltá tu potencial hoy.",
  "🌺 La perseverancia es tu mayor fortaleza.",
  "⚔️ Peleá por tus sueños todos los días.",
  "🧩 Cada tarea que cerrás es una pieza de tu éxito.",
  "🎠 La vida es hermosa cuando actuás con pasión.",
  "💥 Reventá tus límites. Ahora.",
  "🌟 Sé la mejor versión de vos mismo.",
  "🚂 No pares. El impulso es tu mayor riqueza.",
  "🎪 Mostrá de qué estás hecho, che.",
  "🔮 Tu futuro se construye en el presente.",
  "🐉 Despertá el fuego que tenés adentro.",
  "🌠 Apuntá a las estrellas, vas a aterrizar en la luna.",
  "🏋️ Cada esfuerzo te acerca un paso más.",
  "🎸 Tocá la música de tu vida a todo volumen.",
  "🌞 El sol sale para los que se levantan.",
  "🦊 Sé vivo, determinado y auténtico.",
  "🎭 Jugá tu papel con todo el corazón.",
  "💰 Invertí en vos mismo. Es el mejor plazo fijo.",
  "🌀 La acción disuelve cualquier ansiedad. Empezá.",
  "🦄 Sé extraordinario en lo ordinario.",
  "🎯 Una prioridad por vez. Lo vas a lograr.",
  "🌊 El mar de posibilidades te espera. Tirarte.",
  "🔥 Quemá por tus objetivos cada día.",
  "🎆 Hacé de esta jornada un fuego artificial.",
  "🌱 Cada hábito es una semilla para el futuro.",
  "💪 El cansancio es temporal. El orgullo es permanente.",
  "🏆 El éxito es de los que no largan.",
  "⚡ Sé la chispa que enciende tu día.",
  "🌈 Después de la lluvia siempre sale el sol.",
  "🎪 La vida te aplaude cuando das lo mejor.",
  "🔑 La clave del éxito está en tu rutina diaria.",
  "🧭 Mantenete en rumbo. Estás en el camino correcto.",
  "🌻 Girate hacia la luz. Siempre.",
  "💎 Los diamantes se forman bajo presión. Aguantá.",
  "🚀 Lanzate. El resto se va a acomodar.",
  "✨ Cada momento es una chance de empezar de nuevo.",
  "🦁 Rugile a los problemas. Sos más fuerte que ellos.",
  "🎵 Que tu día sea una melodía de logros.",
  "🌅 El amanecer de tu mejor día empieza ahora.",
  "💡 Una buena idea en acción vale más que mil planes.",
  "🏄 Agarrá la ola de la oportunidad. Está ahí.",
  "🎯 Apuntá a tus objetivos con precisión y pasión.",
  "🌍 Podés cambiar tu mundo hoy.",
  "🦋 Transformate. Un paso a la vez.",
  "⭐ Brillás incluso cuando no te das cuenta.",
  "🔥 Tu fuego interior es inextinguible.",
  "🏔️ Toda cumbre empieza con un primer paso.",
  "💫 Creé en vos. Los demás van a seguirte.",
  "🎁 Tenés un talento único. Compartilo con el mundo.",
  "🌺 Crecé con gracia. Expandite con fuerza.",
  "🦅 Elevate por encima de la mediocridad.",
  "🌙 Hasta la noche más oscura termina con un amanecer.",
  "🎶 Componé la sinfonía de tu vida hoy.",
  "💥 Rompé tus barreras. Sos libre.",
  "🌟 Cada versión de vos es una mejora.",
  "🔮 Visualizá tu éxito. Después construilo.",
  "🧠 Tu determinación es más fuerte que cualquier obstáculo.",
  "🐉 Sé legendario en todo lo que emprendas.",
  "🌠 Las estrellas te miran. Dale un buen espectáculo.",
  "🏋️ La fortaleza mental se entrena igual que los músculos.",
  "🎸 Sé el rockstar de tu propia vida.",
  "🌞 Dejá que tu luz brille sin frenos.",
  "🦊 Sé curioso, ágil y sin límites.",
  "🎭 Hoy jugá el rol del héroe.",
  "💰 Cada acción positiva es una inversión en vos.",
  "🌀 El impulso que generás hoy dura toda la semana.",
  "🦄 Lográ lo imposible. Es tu sello.",
  "🎯 Quedate enfocado. El ruido del mundo puede esperar.",
  "🌊 Navegá con confianza. Conocés tu rumbo.",
  "💪 Dale con todo hoy. Tu yo del futuro te lo va a agradecer.",
]

export function getRandomPhrase(): string {
  return motivationalPhrases[Math.floor(Math.random() * motivationalPhrases.length)]
}

export function getDailyPhrase(): string {
  // Cambia una vez por día según la fecha
  const today = new Date()
  const dayIndex =
    (today.getFullYear() * 366 + today.getMonth() * 31 + today.getDate()) %
    motivationalPhrases.length
  return motivationalPhrases[dayIndex]
}
