export const motivationalPhrases: string[] = [
  "🌟 Vos sos tu único límite. Rompelo.",
  "🔥 Cada día es una nueva oportunidad para brillar, che.",
  "💪 La disciplina te lleva más lejos que las ganas.",
  "🚀 Arrancá. El resto se acomoda solo.",
  "🌈 Los sueños grandes piden acción diaria.",
  "⚡ Lo que hacés hoy construye tu mañana.",
  "🎯 Apuntá al progreso, no a la perfección.",
  "🌅 Esta mañana es el comienzo de algo increíble.",
  "💎 Podés más de lo que creés, en serio.",
  "🏆 Los campeones se hacen en los momentos difíciles.",
  "🌱 Cada paso cuenta. Seguí adelante.",
  "✨ Hacé de hoy algo de lo que te vayas a enorgullecer.",
  "🦁 Tené el coraje de tus ambiciones.",
  "🎶 La vida premia a los que se mueven.",
  "🌊 Sé la ola, no la espuma.",
  "🔑 El éxito es la suma de pequeños esfuerzos repetidos.",
  "🧠 Tu cabeza es tu superpoder. Usala bien.",
  "🌻 Florecé donde estás plantado.",
  "⭐ Un día bien empezado está medio ganado.",
  "🦋 La transformación empieza con una decisión.",
  "🏔️ Las mejores vistas vienen de las subidas más duras.",
  "💡 Una idea sin acción es solo un sueño. Actuá.",
  "🎁 Cada mañana es un regalo. Abrilo con intención.",
  "🌙 Ayer ya fue. Hoy es tu turno.",
  "🏄 Montate a tus oportunidades, no las dejes pasar.",
  "🦅 Volá alto. Siempre más alto.",
  "💫 No estás atrasado. Estás justo donde tenés que estar.",
  "🎯 Concentrarte en lo que podés controlar es el juego.",
  "🌍 Cambiá tu día, cambiás tu vida.",
  "🔓 Soltá tu potencial hoy.",
  "🌺 La perseverancia es tu mayor fortaleza.",
  "⚔️ Peleá por tus sueños todos los días.",
  "🧩 Cada tarea que cerrás es una pieza de tu éxito.",
  "🎠 La vida es hermosa cuando actuás con pasión.",
  "💥 Reventá tus límites. Ahora.",
  "🌟 Sé la mejor versión de vos mismo.",
  "🚂 No pares. El impulso es tu mayor riqueza.",
  "🎪 Mostrá de qué estás hecho, che.",
  "🔮 Tu futuro se construye en el presente.",
  "🐉 Despertá el fuego que tenés adentro.",
  "🌠 Apuntá a las estrellas, vas a aterrizar en la luna.",
  "🏋️ Cada esfuerzo te acerca un paso más.",
  "🎸 Tocá la música de tu vida a todo volumen.",
  "🌞 El sol sale para los que se levantan.",
  "🦊 Sé vivo, determinado y auténtico.",
  "🎭 Jugá tu papel con todo el corazón.",
  "💰 Invertí en vos mismo. Es el mejor plazo fijo.",
  "🌀 La acción disuelve cualquier ansiedad. Empezá.",
  "🦄 Sé extraordinario en lo ordinario.",
  "🎯 Una prioridad por vez. Lo vas a lograr.",
  "🌊 El mar de posibilidades te espera. Tirarte.",
  "🔥 Quemá por tus objetivos cada día.",
  "🎆 Hacé de esta jornada un fuego artificial.",
  "🌱 Cada hábito es una semilla para el futuro.",
  "💪 El cansancio es temporal. El orgullo es permanente.",
  "🏆 El éxito es de los que no largan.",
  "⚡ Sé la chispa que enciende tu día.",
  "🌈 Después de la lluvia siempre sale el sol.",
  "🎪 La vida te aplaude cuando das lo mejor.",
  "🔑 La clave del éxito está en tu rutina diaria.",
  "🧭 Mantenete en rumbo. Estás en el camino correcto.",
  "🌻 Girate hacia la luz. Siempre.",
  "💎 Los diamantes se forman bajo presión. Aguantá.",
  "🚀 Lanzate. El resto se va a acomodar.",
  "✨ Cada momento es una chance de empezar de nuevo.",
  "🦁 Rugile a los problemas. Sos más fuerte que ellos.",
  "🎵 Que tu día sea una melodía de logros.",
  "🌅 El amanecer de tu mejor día empieza ahora.",
  "💡 Una buena idea en acción vale más que mil planes.",
  "🏄 Agarrá la ola de la oportunidad. Está ahí.",
  "🎯 Apuntá a tus objetivos con precisión y pasión.",
  "🌍 Podés cambiar tu mundo hoy.",
  "🦋 Transformate. Un paso a la vez.",
  "⭐ Brillás incluso cuando no te das cuenta.",
  "🔥 Tu fuego interior es inextinguible.",
  "🏔️ Toda cumbre empieza con un primer paso.",
  "💫 Creé en vos. Los demás van a seguirte.",
  "🎁 Tenés un talento único. Compartilo con el mundo.",
  "🌺 Crecé con gracia. Expandite con fuerza.",
  "🦅 Elevate por encima de la mediocridad.",
  "🌙 Hasta la noche más oscura termina con un amanecer.",
  "🎶 Componé la sinfonía de tu vida hoy.",
  "💥 Rompé tus barreras. Sos libre.",
  "🌟 Cada versión de vos es una mejora.",
  "🔮 Visualizá tu éxito. Después construilo.",
  "🧠 Tu determinación es más fuerte que cualquier obstáculo.",
  "🐉 Sé legendario en todo lo que emprendas.",
  "🌠 Las estrellas te miran. Dale un buen espectáculo.",
  "🏋️ La fortaleza mental se entrena igual que los músculos.",
  "🎸 Sé el rockstar de tu propia vida.",
  "🌞 Dejá que tu luz brille sin frenos.",
  "🦊 Sé curioso, ágil y sin límites.",
  "🎭 Hoy jugá el rol del héroe.",
  "💰 Cada acción positiva es una inversión en vos.",
  "🌀 El impulso que generás hoy dura toda la semana.",
  "🦄 Lográ lo imposible. Es tu sello.",
  "🎯 Quedate enfocado. El ruido del mundo puede esperar.",
  "🌊 Navegá con confianza. Conocés tu rumbo.",
  "💪 Dale con todo hoy. Tu yo del futuro te lo va a agradecer.",

  // ── 100 nuevas frases ──
  "🌟 Chaque jour est une nouvelle chance de devenir meilleur.",
  "🔥 Le feu qui brûle en toi est plus fort que tout obstacle.",
  "💎 La patience et la persévérance font des miracles.",
  "🚀 Commence maintenant, perfectionne après.",
  "🌈 Ton potentiel est illimité, ose le croire.",
  "⚡ L'action est la seule réponse au doute.",
  "🎯 La concentration est le superpouvoir du succès.",
  "🌅 Ce matin marque le début de quelque chose d'extraordinaire.",
  "💪 Tu es capable de bien plus que tu ne l'imagines.",
  "🏆 Les grands résultats viennent de petites disciplines quotidiennes.",
  "🌱 Progresse chaque jour, même d'un millimètre.",
  "✨ Fais aujourd'hui ce que ton futur toi appréciera.",
  "🦁 Le courage n'est pas l'absence de peur, c'est agir malgré elle.",
  "🎶 Ta vie est une mélodie unique. Joue-la fort.",
  "🌊 Sois l'exception, pas la règle.",
  "🔑 La clé du succès est la régularité, pas l'intensité.",
  "🧠 Ton esprit est ton arme la plus puissante.",
  "🌻 Fleuris là où tu es planté aujourd'hui.",
  "⭐ Un début imparfait vaut mieux qu'une perfection jamais commencée.",
  "🦋 Chaque transformation commence par une décision courageuse.",
  "🏔️ Les défis d'aujourd'hui sont les forces de demain.",
  "💡 L'idée sans action reste un rêve. Agis maintenant.",
  "🎁 Chaque matin est un cadeau. Déballe-le avec intention.",
  "🌙 Hier est passé. Aujourd'hui t'appartient entièrement.",
  "🏄 Les opportunités ne se présentent qu'à ceux qui sont prêts.",
  "🦅 Élève tes standards et ta vie suivra.",
  "💫 Tu n'es pas en retard. Tu es exactement là où tu dois être.",
  "🎯 Reste dans ta zone de discipline, pas de confort.",
  "🌍 Change ta journée, change ta vie.",
  "🔓 Libère le génie qui sommeille en toi.",
  "🌺 La persévérance est la forme d'intelligence la plus rare.",
  "⚔️ Bats-toi pour tes ambitions chaque jour sans exception.",
  "🧩 Chaque tâche accomplie est une brique de ta réussite.",
  "🎠 La passion transforme le travail en art.",
  "💥 Brise tes limites. Elles ne sont que dans ta tête.",
  "🌟 Deviens la meilleure version de toi-même, aujourd'hui.",
  "🚂 Le momentum est ta plus grande richesse. Ne l'arrête pas.",
  "🎪 Montre au monde ce dont tu es capable.",
  "🔮 Ton futur se construit dans les décisions d'aujourd'hui.",
  "🐉 Réveille le feu intérieur qui ne demande qu'à brûler.",
  "🌠 Vise les étoiles même si tu atterris sur la lune.",
  "🏋️ Chaque effort te rapproche de qui tu veux être.",
  "🎸 Joue ta vie à fond, sans retenue.",
  "🌞 La lumière est pour ceux qui se lèvent tôt.",
  "🦊 Sois vif, déterminé et authentique dans tout ce que tu fais.",
  "🎭 Incarne pleinement le rôle du protagoniste de ta vie.",
  "💰 Investis en toi-même. C'est le meilleur rendement possible.",
  "🌀 L'action dissout toute anxiété. Lance-toi maintenant.",
  "🦄 Sois remarquable dans l'ordinaire.",
  "🎯 Une priorité à la fois. Tu y arriveras.",
  "🌊 L'océan des possibilités t'attend. Plonge.",
  "🔥 Brûle pour tes objectifs avec une passion contagieuse.",
  "🎆 Fais de cette journée un feu d'artifice de productivité.",
  "🌱 Chaque habitude est une graine pour un futur abondant.",
  "💪 La fatigue est temporaire. La fierté est permanente.",
  "🏆 Le succès appartient à ceux qui ne lâchent pas.",
  "⚡ Sois l'étincelle qui illumine ta journée.",
  "🌈 Après chaque nuit difficile vient un aube magnifique.",
  "🎪 La vie applaudit ceux qui donnent le meilleur d'eux-mêmes.",
  "🔑 La clé de tout est dans ta routine quotidienne.",
  "🧭 Reste sur ton cap. Tu es sur la bonne voie.",
  "🌻 Tourne-toi vers la lumière. Toujours.",
  "💎 Les diamants se forment sous pression. Tiens bon.",
  "🚀 Lance-toi. Tout le reste s'arrangera.",
  "✨ Chaque instant est une chance de recommencer.",
  "🦁 Rugis face aux défis. Tu es plus fort qu'eux.",
  "🎵 Que ta journée soit une symphonie de réalisations.",
  "🌅 L'aube de ton meilleur jour commence maintenant.",
  "💡 Une bonne idée en action vaut mille plans parfaits.",
  "🏄 Attrape la vague de l'opportunité. Elle est là.",
  "🎯 Vise tes objectifs avec précision et passion.",
  "🌍 Tu peux changer ton monde aujourd'hui. Commence.",
  "🦋 Transforme-toi. Un pas à la fois, sans t'arrêter.",
  "⭐ Tu brilles même quand tu ne t'en rends pas compte.",
  "🔥 Ton feu intérieur est inextinguible. Alimente-le.",
  "🏔️ Tout sommet commence par un premier pas courageux.",
  "💫 Crois en toi. Les autres suivront naturellement.",
  "🎁 Tu as un talent unique. Offre-le au monde.",
  "🌺 Grandis avec grâce. Expanse-toi avec force.",
  "🦅 Élève-toi au-dessus de la médiocrité ambiante.",
  "🌙 Même la nuit la plus sombre se termine par une aube.",
  "🎶 Compose la symphonie de ta vie aujourd'hui.",
  "💥 Brise tes barrières. Tu es libre de tout accomplir.",
  "🌟 Chaque version de toi est une amélioration.",
  "🔮 Visualise ton succès. Puis construis-le brique par brique.",
  "🧠 Ta détermination est plus forte que n'importe quel obstacle.",
  "🐉 Sois légendaire dans tout ce que tu entreprends.",
  "🌠 Les étoiles te regardent. Offre-leur un beau spectacle.",
  "🏋️ La force mentale se développe comme un muscle. Entraîne-la.",
  "🎸 Sois la rockstar de ta propre existence.",
  "🌞 Laisse ta lumière briller sans aucune retenue aujourd'hui.",
  "🦊 Sois curieux, agile et sans limites dans ta vie.",
  "🎭 Joue le rôle du héros dans l'histoire de ta vie.",
  "💰 Chaque action positive est un investissement en toi.",
  "🌀 L'élan que tu génères aujourd'hui dure toute la semaine.",
  "🦄 Accomplis l'impossible. C'est ta marque de fabrique.",
  "🎯 Reste concentré. Le bruit du monde peut attendre.",
  "🌊 Navigue avec confiance. Tu connais ta direction.",
  "💪 Le meilleur moment pour agir était hier. Le second meilleur, c'est maintenant.",
]

export function getRandomPhrase(): string {
  return motivationalPhrases[Math.floor(Math.random() * motivationalPhrases.length)]
}

export function getDailyPhrase(): string {
  // Cambia una vez por día según la fecha
  const today = new Date()
  const dayIndex =
    (today.getFullYear() * 366 + today.getMonth() * 31 + today.getDate()) %
    motivationalPhrases.length
  return motivationalPhrases[dayIndex]
}
